### PR TITLE
fix: add some missing properties

### PR DESCRIPTION
**Pull request by csouchet**
- Add missing properties on `mxGraphExportObject`
- Add missing properties on `mxStyleChange`

### CODE REVIEW

**Review by tbouffard — APPROVED** [review]
✔️ Type verification
- mxStyleChange: https://github.com/jgraph/mxgraph/blob/v4.2.2/javascript/src/js/model/mxGraphModel.js#L2516-L2522
- mxGraphExportObject

**Comment by tbouffard** [comment]
@hungtcs hi, I can merge this PR but I cannot do the `npm publish`
Can you do it please?

**Comment by hungtcs** [comment]
@tbouffard Delighted to announce that version [1.0.8](https://www.npmjs.com/package/@typed-mxgraph/typed-mxgraph/v/1.0.8) has been released. Please check it out.

**Comment by tbouffard** [comment]
Thanks @hungtcs for the new release 💯. We will have a look at it today.
I have created #55 to discuss solution that would let met handle the release and free you from this task when you don't want or don't have time to handle it.

**Pull request merged**
