### PR TITLE
Add missing definitions and shape reference

### PR DESCRIPTION
**Pull request by SupremeVoid**
I am using this package in a project but noticed that a few definitions are missing so I did go ahead and added those I noticed myself. 

mxEditor is still missing it´s definitions but for now I did not have the time to add those as the source code is over 3000 lines of code and it would take some time. 

I also increased the version to 0.0.4-0 since the current released package is 0.0.3-0 and updated a few dependencies.

### CODE REVIEW

**Review by tbouffard — COMMENTED** [review]
Thanks for this pull request 
Can you extract package.json changes to a dedicated pull request to keep this one focused on editor additions?

**Comment by SupremeVoid** [comment]
Alright, will do.

**Comment by SupremeVoid** [comment]
Changes extracted to https://github.com/typed-mxgraph/typed-mxgraph/pull/6

**Review by tbouffard — APPROVED** [review]
Thanks @SupremeVoid for this Pull Request
Notice that I cannot merge it as I don't have rights for that
cc @hungtcs

**Comment by hungtcs** [comment]
@SupremeVoid  Thanks for your PR, sorry to merge so late.

**Comment by hungtcs** [comment]
Changes will be synchronized to [mxgraph-type-definitions](https://github.com/hungtcs/mxgraph-type-definitions).

**Pull request closed without merging**
